### ISSUE TITLE
Payment Options Not Working

### ISSUE THREAD

**Issue by MostertCoder** [Flutterwave/Rave-ReactNative-Wrapper#5]
Hi, I'm having trouble setting the payment options to card. Does it actually do anything? If it does work, is it possible to default to card payment?

I'm using it like in the example:
```javascript
<Rave
  button={props => (
    <Button {...props} title="Pay Now" color="#36b254" />
   )}
   raveKey="FLWPUBK_TEST-75845148130de772994d2169e8fb18b9-X"
   amount={props.payment.Amount}
   currency={'ZAR'}
   country={'ZA'}
   customerEmail={'team9.tech@gmail.com'}
   customerPhone={'08114089344'}
   customer_firstname={'First Name'}
   customer_lastname={'Last Name'}
   ActivityIndicatorColor="#36b254"
   payment_options="card"
   onCancel={props.onCancel}
   onSuccess={props.onSuccess}
   onError={props.onError}
   txref={props.payment.id}
/>
```

**Comment by Corvus97** [comment]
Hello @MostertCoder ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
